curl --header "Content-type: application/json" --request PUT --data '{"id":"Zou_Liping","nick":"Zou_Liping","password":"123456","birthday":"1992-08-03","location":"harbin"}' http://192.168.0.108:9000/user/register
curl --header "Content-type: application/json" --request PUT --data '{"classname":"Goods","individualname":"goods1","uid":"Zou_Liping","title":"goods1","description":"this is a goods","goods_type":"Food"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"classname":"Goods","individualname":"goods2","uid":"Zou_Liping","title":"goods2","description":"this is a goods. Test","goods_type":"Food"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"classname":"Goods","individualname":"goods3","uid":"Zou_Liping","title":"goods3","description":"This is a goods...","goods_type":"Food"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"classname":"WishItem","individualname":"wishitem1","uid":"Zou_Liping","title":"wishitem1","description":"test","goods_type":"MobilePhone"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"classname":"WishItem","individualname":"wishitem2","uid":"Zou_Liping","title":"wishitem2","description":"test2","goods_type":"MobilePhone"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"classname":"WishItem","individualname":"wishitem3","uid":"Zou_Liping","title":"wishitem3","description":"test3","goods_type":"test"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"classname":"WishItem","individualname":"wishitem4","uid":"Zou_Liping","title":"wishitem4","description":"test4","goods_type":"test","added_time":"2013-12-30"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"id1":"Zou_Liping","id2":"Hao_Youqiang","uid":"Zou_Liping"}' http://192.168.0.108:9000/indiv/addrelation
curl --header "Content-type: application/json" --request PUT --data '{"id1":"Zou_Liping","id2":"Zhao_Yixue","uid":"Zou_Liping"}' http://192.168.0.108:9000/indiv/addrelation
curl --header "Content-type: application/json" --request PUT --data '{"id1":"Zou_Liping","id2":"Wang_Jiaqiu","uid":"Zou_Liping"}' http://192.168.0.108:9000/indiv/addrelation

curl --header "Content-type: application/json" --request PUT --data '{"classname":"User","individualname":"Hao_Youqiang","uid":"Hao_Youqiang","nick":"Hao_Youqiang","gender":"true","birthday":"1992-01-01"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"classname":"User","individualname":"Zhao_Yixue","uid":"Zhao_Yixue","nick":"Zhao_Yixue","gender":"false","birthday":"1992-01-02"}' http://192.168.0.108:9000/indiv/update
curl --header "Content-type: application/json" --request PUT --data '{"classname":"User","individualname":"Wang_Jiaqiu","uid":"Wang_Jiaqiu","nick":"Wang_Jiaqiu","gender":"true","birthday":"1992-01-03"}' http://192.168.0.108:9000/indiv/update
